### ISSUE TITLE
wallclock profiling may block Java thread abnormally

### ISSUE THREAD

**Issue by yanglong1010** [async-profiler/async-profiler#769]
hi, Andrei

I found that if java.net.Socket.connect is used in the application code to connect to an IP and port that is unreachable or has a long delay, the wall clock mode may cause the Java thread to be blocked in Socket.connect and cannot return on JDK8 and JDK11. 
The reproducer is below.

The reason is that the signal sent by async-profiler makes the libc poll return in advance, and the OpenJDK implementation will continuously retry the poll without considering the passage of timeout, that is, the same timeout is used every time.

Many profiling projects now use async-profiler as the underlying engine. It is a reasonable or common situation that the IP and port that the application code depends on is temporarily unavailable or misconfigured. In this case, async-profiler should be able to work normally, at least not to make the situation worse. 

The solutions currently thought of are the following:
1. Set the interval to be greater than the timeout time, but this is obviously unacceptable (for example, interval=1000ms, which has little meaning).
2. async-profiler should detect whether the thread's stack is in a method similar to this problem, and automatically pause for a period of time to send a signal to the thread.
3. Modify the implementation in the JDK, and subtract the elapsed time for each retry.

I would like to know your insight on this issue.

``` bash
cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

cat /proc/version
Linux version 3.10.0-1160.80.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Nov 8 15:48:59 UTC 2022

java -version

openjdk version "1.8.0_372"
OpenJDK Runtime Environment (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)

openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.16.0.8-1.el7openjdkportable) (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.16.0.8-1.el7openjdkportable) (build 11.0.16+8-LTS, mixed mode)
```

```java
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;

public class SocketTest {
    public static void main(String[] args) throws IOException {
        Socket socket = new Socket();
        socket.connect(new InetSocketAddress("100.100.27.99", 8080), 1000);
        System.out.println(socket.isConnected());
    }
}
```

```bash
java -agentpath:/path/to/libasyncProfiler.so=start,event=wall,threads,file=profile.html,interval=10ms SocketTest
```

```
pstack 
Thread 2 (Thread 0x7fbc8f9c2700 (LWP 32725)):
#0  0x00007fbc8ec91ddd in poll () from /lib64/libc.so.6
#1  0x00007fbc559ca3a3 in NET_Poll () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-1.el7_9.x86_64/jre/lib/amd64/libnet.so
#2  0x00007fbc559c75bc in Java_java_net_PlainSocketImpl_socketConnect () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-1.el7_9.x86_64/jre/lib/amd64/libnet.so
#3  0x00007fbc78658427 in ?? ()
#4  0x00007fbc8f9c1620 in ?? ()
```
```
jstack
"main" #1 prio=5 os_prio=0 tid=0x00007fbc884ca800 nid=0x7fd5 runnable [0x00007fbc8f9c1000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	- locked <0x0000000747569088> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at SocketTest.main(SocketTest.java:8)
```

**Comment by apangin** [comment]
Thank you for the detailed report. I confirm this is a JDK bug; will submit a JDK issue shortly.
I'll see if async-profiler can do anything to workarount the bug.

**Comment by apangin** [comment]
I have submitted the bug [JDK-8312065](https://bugs.openjdk.org/browse/JDK-8312065) with the test case, evaluation and the proposed fix.

**Comment by yanglong1010** [comment]
Thanks for such a quick reply, I'll keep an eye on the progress of this issue.

**Comment by apangin** [comment]
@yanglong1010 Are you planning to push the JDK fix yourself, or shall I proceed with that?

**Comment by yanglong1010** [comment]
> 

As Yi Yang communicated with you on JBS, I'm going to fix this issue on JDK, and I'm expected to start next week.

**Comment by apangin** [comment]
@yanglong1010 OK, good. Let me know if I can help with anything.

**Comment by yanglong1010** [comment]
> Thank you for fixing the bug in OpenJDK. It might have sense to backport the fix to jdk11u-dev, too.

I will backport it to 8 and 11 in the near future.

**Comment by zdyj3170101136** [comment]
> 感谢您的详细报告。我确认这是一个 JDK bug；很快就会提交 JDK 问题。 我将看看 async-profiler 是否可以采取任何措施来解决该错误。

is this fixed in async-profile ?

**Comment by apangin** [comment]
> is this fixed in async-profile ?

The bug has been fixed in OpenJDK

**Comment by yanglong1010** [comment]
> > is this fixed in async-profile ?
> 
> The bug has been fixed in OpenJDK

[jdk-17u](https://github.com/openjdk/jdk11u-dev/pull/2178)

**Comment by zdyj3170101136** [comment]
> > > 这是在 async-profile 中修复的吗？
> > 
> > 
> > 该错误已在 OpenJDK 中修复
> 
> @zdyj3170101136你的Java版本是什么？ [jdk-17u 修复了](https://github.com/openjdk/jdk17u-dev/pull/1639) Java 11 和 17 的 [jdk-11u 向后移植，只需使用最新的 JDK 版本。](https://github.com/openjdk/jdk11u-dev/pull/2178) jdk-8u还需要一些时间，我保证会做到这一点。
so, for now, it is unsafe to run wall profiler for some version of java process.

**Comment by yanglong1010** [comment]
In our internal product, for JDKs that do not include this fix, we use bytecode rewriting to pause wallclock profiling during Socket.connect execution (on method entry, remove thread from wallclock timer, on return, add it back).

If you use async-profiler directly, the risk exists.
