### ISSUE TITLE
[JDK22] `jfr2flame` errors out with `Invalid string encoding` when converting to flame graph

### ISSUE THREAD

**Issue by sureshg** [async-profiler/async-profiler#857]
## Env
```
$  java --version
openjdk 22-ea 2024-03-19
OpenJDK Runtime Environment (build 22-ea+26-2112)
OpenJDK 64-Bit Server VM (build 22-ea+26-2112, mixed mode, sharing)
```

## Error
```
java.lang.IllegalArgumentException: Invalid string encoding
        at one.jfr.JfrReader.getString(JfrReader.java:515)
        at one.jfr.JfrReader.readActiveSetting(JfrReader.java:200)
        at one.jfr.JfrReader.readEvent(JfrReader.java:142)
        at one.converter.jfr2flame.convert(jfr2flame.java:57)
```
[jdk22.jfr.zip](https://github.com/async-profiler/async-profiler/files/13538130/jdk22.jfr.zip)

**Comment by apangin** [comment]
Thank you for the report. I've pushed the fix.

**Comment by apangin** [comment]
Sorry, I have no exact date for the next release.
