### ISSUE TITLE
Profiling page faults with cstack results in one-deep stack information

### ISSUE THREAD

**Issue by jbellis** [async-profiler/async-profiler#953]
### Describe the bug

$ asprof -e page-faults --cstack vm 4277 -f faults.jfr
[faults.jfr.gz](https://github.com/user-attachments/files/16145053/faults.jfr.gz)

resulted in the attached file

### Expected vs. actual behavior

Expected more stack information beyond "Thread.run"

### Additional Information/Context

The actual thread causing the page faults is this one in jstack
```
"CompactionExecutor:6" #21970 [31886] daemon prio=1 os_prio=4 cpu=1304369.99ms elapsed=8467.74s tid=0x0000724b1c212240 nid=31886 runnable  [0x0000724b2177e000]
   java.lang.Thread.State: RUNNABLE
        at java.io.RandomAccessFile.readBytes0(java.base@22.0.1/Native Method)
        at java.io.RandomAccessFile.readBytes(java.base@22.0.1/RandomAccessFile.java:398)
        at java.io.RandomAccessFile.read(java.base@22.0.1/RandomAccessFile.java:432)
        at io.github.jbellis.jvector.disk.BufferedRandomAccessWriter.checksum(BufferedRandomAccessWriter.java:106)
        at io.github.jbellis.jvector.graph.disk.OnDiskGraphIndexWriter.checksum(OnDiskGraphIndexWriter.java:255)
        - locked <0x0000000348381af0> (a io.github.jbellis.jvector.graph.disk.OnDiskGraphIndexWriter)
        at org.apache.cassandra.index.sai.disk.vector.CompactionGraph.flush(CompactionGraph.java:313)
        at org.apache.cassandra.index.sai.disk.v1.SegmentBuilder$VectorOffHeapSegmentBuilder.flushInternal(SegmentBuilder.java:300)
        at org.apache.cassandra.index.sai.disk.v1.SegmentBuilder.flush(SegmentBuilder.java:424)
        at org.apache.cassandra.index.sai.disk.v1.SSTableIndexWriter.flushSegment(SSTableIndexWriter.java:265)
        at org.apache.cassandra.index.sai.disk.v1.SSTableIndexWriter.complete(SSTableIndexWriter.java:132)
        at org.apache.cassandra.index.sai.disk.StorageAttachedIndexWriter.complete(StorageAttachedIndexWriter.java:202)
        at org.apache.cassandra.index.sai.StorageAttachedIndexBuilder.completeSSTable(StorageAttachedIndexBuilder.java:320)
        at org.apache.cassandra.index.sai.StorageAttachedIndexBuilder.indexSSTable(StorageAttachedIndexBuilder.java:220)
        at org.apache.cassandra.index.sai.StorageAttachedIndexBuilder.build(StorageAttachedIndexBuilder.java:120)
        at org.apache.cassandra.db.compaction.CompactionManager$15.run(CompactionManager.java:1795)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@22.0.1/Executors.java:572)
        at java.util.concurrent.FutureTask.run(java.base@22.0.1/FutureTask.java:317)
        at org.apache.cassandra.concurrent.DebuggableThreadPoolExecutor$FutureLocalSessionWrapper.lambda$new$0(DebuggableThreadPoolExecutor.java:416)
        at org.apache.cassandra.concurrent.DebuggableThreadPoolExecutor$FutureLocalSessionWrapper$$Lambda/0x0000724adb91f4a8.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(java.base@22.0.1/FutureTask.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@22.0.1/ThreadPoolExecutor.java:1144)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@22.0.1/ThreadPoolExecutor.java:642)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.runWith(java.base@22.0.1/Thread.java:1583)
        at java.lang.Thread.run(java.base@22.0.1/Thread.java:1570)
```

### Async-profiler version

Async-profiler 3.0 built on Jan 20 2024

### Environment details

Ubuntu 24.04 on AWS m7i.2xlarge (Linux ip-172-31-64-111 6.8.0-1010-aws #10-Ubuntu SMP Thu Jun 13 17:36:15 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux)

Oracle JDK 22.0.1

**Comment by jbellis** [comment]
[faults2.jfr.gz](https://github.com/user-attachments/files/16145587/faults2.jfr.gz)

Today I was not able to reproduce (different VM instance, everything else is the same).  I got the attached results which are in line with expectations.

**Comment by apangin** [comment]
Thank you for the detailed report.
I think the explanation is simple: the application was idle in the first case (faults.jfr), while it was under load in the second case (faults2.jfr).
You may see this by opening jfr recordings in JDK Mission Control and searching for CPU Load events:

### faults.jfr
<img width="559" alt="faults" src="https://github.com/async-profiler/async-profiler/assets/1749416/e014c452-5e4f-404d-889d-9fea0cd1dfc9">

### faults2.jfr
<img width="561" alt="faults2" src="https://github.com/async-profiler/async-profiler/assets/1749416/cd38c7f8-0d03-473e-b11f-917ea6ebbac3">

Also note the numbers of samples on the first flame graph (60) vs. the second graph (256K).

Page fault events in the first profile seem to originate from some periodic process that starts a new thread every second. The fault occurs early at thread startup, when there is no Java code executed yet - hence a single `Thread.run` frame.
<img width="259" alt="events" src="https://github.com/async-profiler/async-profiler/assets/1749416/7a5288c9-c48a-407d-b1f4-1693cb929113">

**Comment by jbellis** [comment]
Thanks. Sorry for the noise!
