### ISSUE TITLE
Add a JFR merge feature

### ISSUE THREAD

**Issue by rus-99-pk** [async-profiler/async-profiler#991]
### Describe the feature

Hello, @apangin, @Artyomcool!

I suggest to add merge feature for JFR files, because it's not working using native tools.

### Converting all JFR files into one
```Bash
$ jdk-21.0.1+12/bin/jfr assemble ./ /tmp/file.jfr

Assembling files... 

profile-20240908-165531.jfr
profile-20240908-175531.jfr

Finished.
```
### Trying to create heatmap (from [this](https://github.com/Artyomcool/async-profiler/tree/heatmap-2) repo)
```Bash
$ jdk-21.0.1+12/bin/java -jar jfr-converter.jar -o heatmap /tmp/file.jfr /tmp/test.html
Converting file.jfr -> test.html Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at one.convert.JfrConverter.convertJavaClassName(JfrConverter.java:139)
	at one.heatmap.SymbolTable.convertClassName(SymbolTable.java:157)
	at one.heatmap.SymbolTable.orderedKeys(SymbolTable.java:147)
	at one.heatmap.MethodCache.orderedSymbolTable(MethodCache.java:157)
	at one.heatmap.Heatmap.evaluate(Heatmap.java:72)
	at one.heatmap.Heatmap.dump(Heatmap.java:89)
	at one.convert.JfrToHeatmap.dump(JfrToHeatmap.java:70)
	at one.convert.JfrToHeatmap.convert(JfrToHeatmap.java:81)
	at Main.convert(Main.java:60)
	at Main.main(Main.java:46)
```

* * *

## Example 2 (native Linux tool):
```Bash
$ cat ./profile-* >> /tmp/file.jfr
```

```Bash
$ jdk-21.0.1+12/bin/java -jar jfr-converter.jar -o heatmap /tmp/file.jfr /tmp/test.html
Converting file.jfr -> test.html Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at one.convert.JfrConverter.convertJavaClassName(JfrConverter.java:139)
	at one.heatmap.SymbolTable.convertClassName(SymbolTable.java:157)
	at one.heatmap.SymbolTable.orderedKeys(SymbolTable.java:147)
	at one.heatmap.MethodCache.orderedSymbolTable(MethodCache.java:157)
	at one.heatmap.Heatmap.evaluate(Heatmap.java:72)
	at one.heatmap.Heatmap.dump(Heatmap.java:89)
	at one.convert.JfrToHeatmap.dump(JfrToHeatmap.java:70)
	at one.convert.JfrToHeatmap.convert(JfrToHeatmap.java:81)
	at Main.convert(Main.java:60)
	at Main.main(Main.java:46)
```

* * *

## And now trying to convert a one file (before merge)
```Bash
$ jdk-21.0.1+12/bin/java -jar jfr-converter.jar -o heatmap ./profile-20240908-165531.jfr /tmp/test.html
Converting profile-20240908-165531.jfr -> test.html # 0.782 s
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by apangin** [comment]
Sorry, it's not clear what _feature_  exactly you are proposing.
Merging JFRs is possible with either of two approaches you described: by using `jfr assemble` or by simply concatenating files.

As to exception, it comes from a not-yet-released code which has not been even integrated in async-profiler. 
If you have feedback on #944, please comment in the PR instead.
Thanks.
